version: '3.5'

services:
  docker-caldera:
    build: ./
    container_name: docker-caldera
    restart: always
    ports:
      - "8888:8888"
      - "7010:7010/tcp"
      - "7010:7010/udp"
      - "7012:7012"
    networks:
      caldera:

networks:
  caldera:
    driver: bridge