version: '3.5'

services:
  docker-caldera:
    build: ./
    container_name: docker-caldera
    restart: always
    ports:
      - "8888:8888"
    networks:
      caldera:

networks:
  caldera:
    driver: bridge