version: '3.5'
services:
  caldera-evals:
    image: cyb3rward0g/docker-caldera:evals-042220
    container_name: caldera-evals
    volumes:
      - ./conf/4fb34bde-b06d-445a-a146-8e35f79ce546.yml:/usr/src/app/plugins/evals/data/sources/4fb34bde-b06d-445a-a146-8e35f79ce546.yml
    restart: always
    environment:
      CALDERA_RED_ADMIN_NAME: ${CALDERA_RED_ADMIN_NAME}
      CALDERA_RED_ADMIN_PASSWORD: ${CALDERA_RED_ADMIN_PASSWORD}
    ports:
      - "8888:8888"
      - "7010:7010/tcp"
      - "7011:7011/udp"
      - "7012:7012"
    networks:
      caldera:

networks:
  caldera:
    driver: bridge
