api_key_blue: BLUEADMIN123
api_key_red: ADMIN123
encryption_key: ADMIN123
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://127.0.0.1:8888
app.contact.tcp: 127.0.0.1:7010
app.contact.udp: 127.0.0.1:7011
app.contact.websocket: 127.0.0.1:7012
crypt_salt: REPLACE_WITH_RANDOM_VALUE
exfil_dir: /tmp
plugins:
- sandcat
- mock
- stockpile
- response
- compass
- ssl
- atomic
- gameboard
- training
- access
- manx
port: 8888
reports_dir: /tmp
users:
  blue:
    blue: admin
  red:
    red: admin